import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "react-hot-toast"
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}

<Toaster
  position="top-center"
  gutter={12}
  containerStyle={{
    top: 24,
  }}
  toastOptions={{
    duration: 3000,
    style: {
      borderRadius: "14px",
      background: "#ffffff",
      color: "#111827",
      boxShadow: "0 20px 40px rgba(0,0,0,0.15)",
      padding: "16px 18px",
      fontSize: "14px",
      fontWeight: 500,
      border: "1px solid #e5e7eb",
    },

    success: {
      style: {
        border: "1px solid #4ade80",
        background: "#f0fdf4",
      },
      iconTheme: {
        primary: "#16a34a",
        secondary: "#dcfce7",
      },
    },

    error: {
      style: {
        border: "1.5px solid #ef4444",
        background: "#fef2f2",
      },
      iconTheme: {
        primary: "#dc2626",
        secondary: "#fee2e2",
      },
    },
  }}
/>
      </body>
    </html>
  );
}
